routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    Route::resource('products', ProductController::class);

    Route::get('/changePassword',[UserController::class, 'changePasswordView'])->name('changePassword');
    
    Route::post('changePasswordUpdate',[UserController::class, 'changePasswordUpdate'])->name('changePasswordUpdate');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php
    
namespace App\Http\Controllers;
    
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\URL;
use DB;
use Hash;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Auth;
use App\Utility\Utility;
    
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $basenameUrl = basename(URL::current());
        $data = User::orderBy('id','DESC')->paginate(5);
        return view('users.index',compact('data','basenameUrl'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }
    
     public function changePasswordView()
    {
        $basenameUrl = basename(URL::current());
  $user = User::find(Auth::id());

        return view('users.changePasswordView',compact('basenameUrl','user'));
       
    }

    public function changePasswordUpdate(Request $request){

        


     /*    if($request->filled('oldPassword')) {
        dd('user_id is not empty.');
    } else {
        dd('user_id is empty.');
    }
    exit();*/

      if($request->filled('oldPassword')){

      
         if (!(Hash::check($request->get('oldPassword'), Auth::user()->password))) {
            // The passwords matches
            return redirect()->back()->with("failed","Your current password does not matches with the password you provided. Please try again.");
        }
      }




 if($request->filled('oldPassword')){
        if(strcmp($request->get('oldPassword'), $request->get('newPassword')) == 0){
            //Current password and new password are same
            return redirect()->back()->with("failed","New Password cannot be same as your current password. Please choose a different password.");
        }
    }


    //Change Password
        $user = Auth::user();
        $user->name = $request->filled('name')? $request->get('name') :$user->name;
        $user->email = $request->filled('email')? $request->get('email') :$user->email;
        $user->phone = $request->filled('phone')? $request->get('phone') :$user->phone;
        $user->password = $request->filled('newPassword')? Hash::make($request->get('newPassword')):$user->password ;
        $user->save();
        return redirect()->back()->with("success","updated successfully !");


    }
    
    public function create()
    {
        $basenameUrl = basename(URL::current());
        $roles = Role::pluck('name','name')->all();
        return view('users.create',compact('roles','basenameUrl'));
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
    
        $user = User::create($input);
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('users.index')
                        ->with('success','User created successfully');
    }
    
      public function changePassword____al_mamun(Request $request) {
        if (!(Hash::check($request->get('oldPassword'), Auth::user()->password))) {
            // The passwords matches
            return redirect()->back()->with("failed","Your current password does not matches with the password you provided. Please try again.");
        }

        if(strcmp($request->get('oldPassword'), $request->get('newPassword')) == 0){
            //Current password and new password are same
            return redirect()->back()->with("failed","New Password cannot be same as your current password. Please choose a different password.");
        }

        $validatedData = $request->validate([
            'oldPassword' => 'required',
            'newPassword' => 'required|string|min:6|confirmed',
            'newPassword_confirmation' => 'required|same:newPassword'
        ]);

        //Change Password
        $user = Auth::user();
        $user->password = Hash::make($request->get('newPassword'));
        $user->save();
        return redirect()->back()->with("status","Password changed successfully !");
    }
    public function show($id)
    {


        $user = User::find($id);
        return view('users.show',compact('user'));
    }
    
    

    public function edit($id)
    {
        $basenameUrl = basename(URL::current());
        $user = User::find($id);
        $roles = Role::pluck('name','name')->all();
        $userRole = $user->roles->pluck('name','name')->all();
    
        return view('users.edit',compact('user','roles','userRole','basenameUrl'));
    }
    
    
    public function update(Request $request, $id)
    {
        

        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'same:confirm-password',
            'roles' => 'required'
        ]);
    
        $input = $request->all();
        if(!empty($input['password'])){ 
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = Arr::except($input,array('password'));    
        }
    
        $user = User::find($id);
        $user->update($input);
        DB::table('model_has_roles')->where('model_id',$id)->delete();
    
        $user->assignRole($request->input('roles'));
    
        return redirect()->route('users.index')
                        ->with('success','User updated successfully');
    }


  
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('users.index')
                        ->with('success','User deleted successfully');
    }
}

resources/views/users/changePasswordView.blade.php
@extends('layouts.app')

@section('title', 'Users Edit Form')


@section('js')

<script>

</script>


@endsection
@section('css')

@endsection


@section('content')
<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->

    @include('pages/include/beginPageHeader')

    {{-- @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
    @endforeach
    </ul>
</div>
@endif--}}
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <div class="tabbable-line boxless tabbable-reversed">

            <div class="tab-content">
                <div class="tab-pane active" id="tab_0">

                    {{-- <div class="portlet box blue-hoki">--}}
                    <div class="portlet box blue">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-list-alt"></i>User Edit Form
                            </div>
                            <!-- <div class="actions">
                                <a class="btn btn-danger btn-icon-only btn-default" href="{{route('users.index')}}">
                                    <i class="fa fa-list bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-search-plus bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-pencil" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-trash-o bigger-130" style="color:#fff;"></i>
                                </a>
                            </div> -->

                        </div>
                        <div class="portlet-body form">
                            <!-- BEGIN FORM-->


                            <form action="{{'changePasswordUpdate'}}" method="post" class="form-horizontal" enctype="multipart/form-data">
                                  @csrf

                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Name</label>
                                        <div class="col-md-4">
                                            <input name="name" value="{{$user->name}}" type="text" class="form-control" placeholder="Enter User Name">


                                            {!! $errors->first('name', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Email</label>
                                        <div class="col-md-4">
                                            <input name="email" value="{{$user->email}}" type="email" class="form-control" placeholder="Enter User Email">


                                            {!! $errors->first('email', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Phone</label>
                                        <div class="col-md-4">
                                            <input name="phone" value="{{$user->phone}}" type="number" class="form-control" placeholder="Enter User Phone">


                                            {!! $errors->first('phone', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Current Password</label>
                                        <div class="col-md-4">
                                            <input name="oldPassword" value="{{ old('password') }}" type="password" class="form-control" placeholder="Enter User Current password">


                                            {!! $errors->first('oldPassword', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">New Password</label>
                                        <div class="col-md-4">
                                            <input name="newPassword" value="{{ old('confirm-password') }}" type="password" class="form-control" placeholder="Enter New Password">


                                            {!! $errors->first('newPassword', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>




                                </div>

                                <div class="form-actions top">
                                    <div class="row">
                                        <div class="col-md-offset-4 col-md-8">
                                            <button type="submit" class="btn green">Submit</button>
                                            <button type="button" class="btn default">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <!-- END FORM-->
                        </div>
                    </div>


                </div>


            </div>
        </div>
    </div>
</div>


</div>
<!-- END CONTENT BODY -->
@endsection

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', 'Users Create')


@section('js')

<script>

</script>


@endsection
@section('css')

@endsection


@section('content')
<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->

    @include('pages/include/beginPageHeader')

    {{-- @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
    @endforeach
    </ul>
</div>
@endif--}}
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <div class="tabbable-line boxless tabbable-reversed">

            <div class="tab-content">
                <div class="tab-pane active" id="tab_0">

                    {{-- <div class="portlet box blue-hoki">--}}
                    <div class="portlet box blue">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-list-alt"></i>User Form
                            </div>
                            <!-- <div class="actions">
                                <a class="btn btn-danger btn-icon-only btn-default" href="{{route('users.index')}}">
                                    <i class="fa fa-list bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-search-plus bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-pencil" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-trash-o bigger-130" style="color:#fff;"></i>
                                </a>
                            </div> -->

                        </div>
                        <div class="portlet-body form">
                            <!-- BEGIN FORM-->



                            <form action="{{route('users.store')}}" method="post" class="form-horizontal" enctype="multipart/form-data">
                                @csrf
                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Name</label>
                                        <div class="col-md-4">
                                            <input name="name" value="{{ old('name') }}" type="text" class="form-control" placeholder="Enter User Name">


                                            {!! $errors->first('name', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Email</label>
                                        <div class="col-md-4">
                                            <input name="email" value="{{ old('email') }}" type="email" class="form-control" placeholder="Enter User Email">


                                            {!! $errors->first('email', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Phone</label>
                                        <div class="col-md-4">
                                            <input name="phone" value="{{ old('phone') }}" type="phone" class="form-control" placeholder="Enter User Phone">


                                            {!! $errors->first('phone', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Password</label>
                                        <div class="col-md-4">
                                            <input name="password" value="{{ old('password') }}" type="password" class="form-control" placeholder="Enter User password">

                                            {!! $errors->first('password', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Confirm Password</label>
                                        <div class="col-md-4">
                                            <input name="confirm-password" value="{{ old('confirm-password') }}" type="password" class="form-control" placeholder="Enter Confirm Password">

                                            {!! $errors->first('confirm-password', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">Role</label>
                                        <div class="col-md-4">
                                            <select id="single" name="roles" class="form-control select2">
                                                <option value=""></option>
                                                @foreach($roles as $role)
                                                <option value="{{$role}}">{{$role}}</option>
                                                @endforeach

                                            </select>
                                            {!! $errors->first('roles', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>



                                </div>

                                <div class="form-actions top">
                                    <div class="row">
                                        <div class="col-md-offset-4 col-md-8">
                                            <button type="submit" class="btn green">Submit</button>
                                            <button type="button" class="btn default">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <!-- END FORM-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


</div>
<!-- END CONTENT BODY -->
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Users Edit Form')


@section('js')

<script>

</script>


@endsection
@section('css')

@endsection


@section('content')
<!-- BEGIN CONTENT BODY -->
<div class="page-content">
    <!-- BEGIN PAGE HEADER-->

    @include('pages/include/beginPageHeader')

    {{-- @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Whoops!</strong> There were some problems with your input.<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
    @endforeach
    </ul>
</div>
@endif--}}
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <div class="tabbable-line boxless tabbable-reversed">

            <div class="tab-content">
                <div class="tab-pane active" id="tab_0">

                    {{-- <div class="portlet box blue-hoki">--}}
                    <div class="portlet box blue">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-list-alt"></i>User Edit Form
                            </div>
                            <!-- <div class="actions">
                                <a class="btn btn-danger btn-icon-only btn-default" href="{{route('users.index')}}">
                                    <i class="fa fa-list bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-search-plus bigger-130" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-pencil" style="color:#fff;"></i>
                                </a>
                                <a class="btn btn-danger btn-icon-only btn-default" href="#">
                                    <i class="fa fa-trash-o bigger-130" style="color:#fff;"></i>
                                </a>
                            </div> -->

                        </div>
                        <div class="portlet-body form">
                            <!-- BEGIN FORM-->


                            <form action="{{route('users.update',$user->id)}}" method="post" class="form-horizontal" enctype="multipart/form-data">

                                {{ method_field('PATCH') }}
                                {{ csrf_field() }}

                                <div class="form-body">
                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Name</label>
                                        <div class="col-md-4">
                                            <input name="name" value="{{ $user->name }}" type="text" class="form-control" placeholder="Enter User Name">


                                            {!! $errors->first('name', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Email</label>
                                        <div class="col-md-4">
                                            <input name="email" value="{{ $user->email }}" type="email" class="form-control" placeholder="Enter User Email">


                                            {!! $errors->first('email', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Phone</label>
                                        <div class="col-md-4">
                                            <input name="phone" value="{{ $user->phone }}" type="number" class="form-control" placeholder="Enter User Phone">


                                            {!! $errors->first('phone', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Password</label>
                                        <div class="col-md-4">
                                            <input name="password" value="{{ old('password') }}" type="password" class="form-control" placeholder="Enter User password">


                                            {!! $errors->first('password', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-3 control-label">User Confirm Password</label>
                                        <div class="col-md-4">
                                            <input name="confirm-password" value="{{ old('confirm-password') }}" type="password" class="form-control" placeholder="Enter Confirm Password">


                                            {!! $errors->first('confirm-password', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>


                                    <div class="form-group">

                                        <label class="col-md-3 control-label">Role </label>
                                        <div class="col-md-4">
                                            <select id="single" name="roles" class="form-control select2">
                                                <option value=""></option>

                                                @foreach($roles as $item)

                                                @foreach($userRole as $value)
                                                <option value="{{$item}}" {{ $item == $value ? 'selected' : '' }}>{{$item}}</option>
                                                @endforeach

                                                @endforeach


                                            </select>
                                            {!! $errors->first('roles', '<small class="text-danger">:message</small>') !!}
                                        </div>
                                    </div>


                                </div>

                                <div class="form-actions top">
                                    <div class="row">
                                        <div class="col-md-offset-4 col-md-8">
                                            <button type="submit" class="btn green">Submit</button>
                                            <button type="button" class="btn default">Cancel</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <!-- END FORM-->
                        </div>
                    </div>


                </div>


            </div>
        </div>
    </div>
</div>


</div>
<!-- END CONTENT BODY -->
@endsection

resources/views/users/show.blade.php
@extends('layouts.app')


@section('content')
<div class="page-content">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show User</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $user->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Email:</strong>
                {{ $user->email }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Roles:</strong>
                @if(!empty($user->getRoleNames()))
                @foreach($user->getRoleNames() as $v)
                <label class="badge badge-success">{{ $v }}</label>
                @endforeach
                @endif
            </div>
        </div>
    </div>
</div>

@endsection